name: Update The Safe
on:
    schedule:
        - cron: "0 5 * * *"
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # Run update.js
            - name: Run update.js
              run: node update -1 && node update -2 && node update -3 && node gddl
